language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
      - rust: nightly
sudo: false
script:
    - cargo build --manifest-path mles-utils/Cargo.toml
    - cargo test --manifest-path mles-utils/Cargo.toml 
    - cargo build --manifest-path mles/Cargo.toml
    - cargo test --manifest-path mles/Cargo.toml 
    - cargo build --manifest-path mles-client/Cargo.toml
    - cargo test --manifest-path mles-client/Cargo.toml 

notifications:
    email:
        on_success: never
        os:
            - linux
            - osx
