[package]
name = "mles-utils"
version = "0.9.4"

authors = ["jq-rs"]
description = "Mles-utils for Mles server and clients"
license = "GPL-3.0"
repository = "https://github.com/jq-rs/mles-rs"
documentation = "https://docs.rs/mles-utils"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_cbor = "0.6"
serde_bytes = "0.10"
byteorder = "1.0"
siphasher = "0.2"
 
[lib]
test = true
