[package]
name = "mles-utils"
version = "0.1.1"
authors = ["jq-rs <juhamatk@gmail.com>"]
description = "Mles-utils for Mles server and client(s)"
license = "GPL-3.0"

[dependencies]
serde = "0.8.19"
serde_derive = "0.8.19"
serde_cbor = "0.4"
byteorder = "1.0.0"
