[package]
name = "mles"
version = "0.4.2"
authors = ["jq-rs"]
description = "Mles - a distributed publish/subscribe database server"
license = "GPL-3.0"
repository = "https://github.com/jq-rs/mles-rs"

[dependencies]
mles-utils = "0.4"
