[package]
name = "mles"
version = "0.1.0"
authors = ["jq-rs <juhamatk@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
serde = "0.8.19"
serde_derive = "0.8.19"
serde_cbor = "0.4"
byteorder = "1.0.0"
