[package]
name = "mles-client"
version = "0.9.1"
authors = ["jq-rs"]
description = "Mles-client, a distributed database server example (chat) client"
license = "GPL-3.0"
repository = "https://github.com/jq-rs/mles-rs"
documentation = "http://mles.io"

[dependencies]
mles-utils = "0.9"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
bytes = "0.4"
tokio-proto = "0.1"
tokio-service = "0.1"
websocket = {version = "0.19", default-features=false}
