[package]
name = "mles-client"
version = "0.1.0"
authors = ["jq-rs <juhamatk@gmail.com>"]
description = "Mles-client, a distributed database server example (chat) client"
license = "GPL-3.0"

[dependencies]
mles-utils = "0.1.1"
futures = "0.1"
tokio-core = "0.1"
